import type { NextConfig } from "next";
import { initOpenNextCloudflareForDev } from "@opennextjs/cloudflare";

// Wire the OpenNext Cloudflare adapter for `next dev` so bindings + env vars
// mirror production (per plan T013, constitution Principle V — Cloudflare Workers).
// Fire-and-forget (next.config.ts is compiled without top-level-await support).
void initOpenNextCloudflareForDev();

// Derive the Supabase Storage hostname from NEXT_PUBLIC_SUPABASE_URL so
// signed URLs generated by `supabase.storage.createSignedUrls` pass the
// `next/image` remote-host whitelist. Falls back to the `*.supabase.co`
// hostname glob for local (127.0.0.1:54321 is handled via `127.0.0.1`
// explicit entry below).
type RemotePattern = NonNullable<
  NonNullable<NextConfig["images"]>["remotePatterns"]
>[number];

function supabaseRemotePatterns(): RemotePattern[] {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const patterns: RemotePattern[] = [
    // Local Supabase (make up)
    { protocol: "http", hostname: "127.0.0.1", port: "54321" },
    { protocol: "http", hostname: "localhost", port: "54321" },
    // Any cloud Supabase project — path restricted to Storage so arbitrary
    // URLs on these subdomains can't be rendered via next/image.
    { protocol: "https", hostname: "*.supabase.co", pathname: "/storage/**" },
    { protocol: "https", hostname: "*.supabase.in", pathname: "/storage/**" },
  ];
  if (url) {
    try {
      const parsed = new URL(url);
      patterns.push({
        protocol: parsed.protocol.replace(":", "") as "http" | "https",
        hostname: parsed.hostname,
        port: parsed.port || undefined,
        pathname: "/storage/**",
      });
    } catch {
      // Ignore invalid URL — cloud pattern above still covers it.
    }
  }
  return patterns;
}

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      // Google profile avatars (Supabase OAuth stores the URL in
      // user_metadata.avatar_url / picture). Variants are lh3/lh4/lh5/lh6.
      { protocol: "https", hostname: "lh3.googleusercontent.com" },
      { protocol: "https", hostname: "lh4.googleusercontent.com" },
      { protocol: "https", hostname: "lh5.googleusercontent.com" },
      { protocol: "https", hostname: "lh6.googleusercontent.com" },
      // Supabase Storage signed URLs — auto-derived.
      ...supabaseRemotePatterns(),
    ],
  },
};

export default nextConfig;
